name: Tests

on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux]

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha16/premake-5.0.0-alpha16-linux.tar.gz
          tar -xvf premake-5.0.0-alpha16-linux.tar.gz
          sudo chmod a+x premake5
          sudo mv premake5 /usr/local/bin

      - name: Build
        run: |
          ./build.sh clean
          ./build.sh
          ./build.sh release

      - name: Tests
        run: |
          cd dev
          ./test.sh

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      # Using wget from powershell take no time (using choco to install it takes 1-2 minutes)
      - name: Download Premake5
        shell: powershell
        run: |
          echo GITHUB_WORKSPACE is ${{ github.workspace }}
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta1/premake-5.0.0-beta1-windows.zip -OutFile ${{ github.workspace }}\premake-5.0.0-beta1-windows.zip
          Expand-Archive -LiteralPath ${{ github.workspace }}\premake-5.0.0-beta1-windows.zip -DestinationPath C:\
          ls C:\

      # - name: Install
      #   shell: bash # mingw
      #   run: |
      #     unzip premake-5.0.0-beta1-windows.zip
      #     chmod a+x premake5.exe
      #     mkdir -p $HOME/.local/bin
      #     mv premake5.exe $HOME/.local/bin
      #     echo "$HOME/.local/bin" >> $GITHUB_PATH

      # - name: Build
      #   shell: bash #mingw
      #   run: |
      #     ./build.sh
      #     ./build.sh release


      # - name: Tests
      #   shell: bash
      #   run: |
      #     cd dev
      #     ./test.sh

  build-macos:
    runs-on: macOS-latest

    strategy:
      matrix:
        platform: [macOS]

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha16/premake-5.0.0-alpha16-macosx.tar.gz
          tar -xvf premake-5.0.0-alpha16-macosx.tar.gz
          sudo chmod a+x premake5
          sudo mv premake5 /usr/local/bin

      - name: Build
        run: |
          ./build.sh
          ./build.sh release

      - name: Tests
        if: matrix.platform == 'macOS'
        run: |
          echo Testing for ${{matrix.platform}}
          cd dev
          ./test.sh
